use std::fs;
use std::io::{BufRead, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use anyhow::{anyhow, Context, Result};
use patchkit::apply::{apply_fuzzy, dry_run, ApplyOptions};
use patchkit::unified::{parse_patches, splitlines, Hunk, PlainOrBinaryPatch};
use serde::Deserialize;

use crate::editor::discover_editor_instances;
use crate::i18n::{t, tr};

const REGISTRY_URL: &str = "https://download.packages.unity.com/com.unity.pipeline/";
const PACKAGE_ID: &str = "com.unity.pipeline";
// Generated by build.rs from `patches/<补丁集>/*.patch`：EMBEDDED_PATCHES =
// (补丁集名, 文件名, 内容)，PATCH_SET_RULES = (补丁集名, 生效起始版本)，
// DEFAULT_PATCH_SET 为无规则命中时的兜底集合。
include!(concat!(env!("OUT_DIR"), "/embedded_patches.rs"));

const PATCHS_DIR_NAME: &str = "patchs";
const SYSTEM_DIR_NAME: &str = "system";
const CUSTOM_DIR_NAME: &str = "custom";
const CUSTOM_PATCH_PREFIX: &str = "modify_unity_local_";

pub struct Options {
    /// Skip the interactive picker and use this version.
    pub version: Option<String>,
    /// Skip the picker and use the registry's `dist-tags.latest`.
    pub latest: bool,
    /// Never re-download when the tarball is already in `downloads/`.
    pub keep_cache: bool,
}

#[derive(Debug, Deserialize)]
struct Packument {
    #[serde(default, rename = "dist-tags")]
    dist_tags: Option<DistTags>,
    #[serde(default)]
    versions: std::collections::BTreeMap<String, VersionEntry>,
}

#[derive(Debug, Deserialize)]
struct DistTags {
    #[serde(default)]
    latest: Option<String>,
}

#[derive(Debug, Deserialize)]
struct VersionEntry {
    #[serde(default)]
    dist: Option<Dist>,
}

#[derive(Debug, Deserialize)]
struct Dist {
    #[serde(default)]
    tarball: Option<String>,
    #[serde(default)]
    shasum: Option<String>,
}

pub fn run(opts: Options) -> Result<()> {
    // Step 1: require a running Unity Editor up front. No open project means
    // there's nothing to install into, so bail before touching the network.
    let target_project = match pick_target_project()? {
        Some(p) => p,
        None => {
            return Err(anyhow!("{}", t("install.no_editor_instance")));
        }
    };
    println!("{}", tr("install.target_project", &[&target_project.display()]));

    println!("{}", tr("install.fetching_versions", &[&PACKAGE_ID]));
    let body = http_get_text(REGISTRY_URL).context(t("install.fetch_packument_failed"))?;
    let packument: Packument = serde_json::from_str(&body)
        .with_context(|| tr("install.parse_json_response_failed", &[&REGISTRY_URL]))?;

    let latest = packument.dist_tags.as_ref().and_then(|t| t.latest.clone());
    let versions = sort_versions(packument.versions.keys().cloned().collect());
    if versions.is_empty() {
        return Err(anyhow!("{}", t("install.empty_version_list")));
    }

    let chosen = pick_version(&opts, &versions, latest.as_deref(), &packument)?;
    let entry = packument
        .versions
        .get(&chosen)
        .ok_or_else(|| anyhow!("{}", tr("install.version_not_found", &[&chosen])))?;
    let tarball = entry
        .dist
        .as_ref()
        .and_then(|d| d.tarball.as_deref())
        .ok_or_else(|| anyhow!("{}", tr("install.missing_dist_tarball", &[&chosen])))?;
    let expected_shasum = entry.dist.as_ref().and_then(|d| d.shasum.as_deref());

    let cwd = std::env::current_dir()?;
    let downloads_dir = cwd.join("downloads");
    fs::create_dir_all(&downloads_dir).with_context(|| {
        tr("install.create_downloads_dir_failed", &[&downloads_dir.display()])
    })?;

    let file_name = tarball_file_name(tarball, &chosen);
    let tarball_path = downloads_dir.join(&file_name);

    if tarball_path.exists() && opts.keep_cache {
        println!("{}", tr("install.using_cache", &[&tarball_path.display()]));
    } else {
        println!(
            "{}",
            tr("install.downloading", &[&tarball, &tarball_path.display()])
        );
        download(tarball, &tarball_path)?;
    }

    if let Some(sha) = expected_shasum {
        // Verify via the sha1 crate — no external `certutil` / `shasum` needed.
        if let Ok(actual) = sha1_hex(&tarball_path) {
            if !actual.eq_ignore_ascii_case(sha) {
                return Err(anyhow!(
                    "{}",
                    tr("install.sha1_mismatch", &[&sha, &actual])
                ));
            }
            println!("{}", tr("install.sha1_ok", &[&actual]));
        }
    }

    // Extract into downloads/<basename-of-tarball>/ so each version sits in its
    // own folder, alongside the original .tgz for cache reuse.
    let extract_stem = tarball_stem(&file_name);
    let extract_root = downloads_dir.join(&extract_stem);
    if extract_root.exists() {
        // Clean any stale contents so a re-run doesn't blend two versions.
        fs::remove_dir_all(&extract_root).with_context(|| {
            tr("install.clean_extract_dir_failed", &[&extract_root.display()])
        })?;
    }
    fs::create_dir_all(&extract_root).with_context(|| {
        tr("install.create_extract_dir_failed", &[&extract_root.display()])
    })?;

    println!(
        "{}",
        tr(
            "install.extracting",
            &[&tarball_path.display(), &extract_root.display()]
        )
    );
    extract_tarball(&tarball_path, &extract_root)?;

    let package_dir = extract_root.join("package");
    if !package_dir.exists() {
        // Non-standard tarball layout (no "package/" root). We can still report
        // the extraction, but patch + copy target expects the UPM layout.
        println!("{}", tr("install.tarball_extracted", &[&extract_root.display()]));
        return Err(anyhow!("{}", t("install.missing_package_dir")));
    }
    println!("{}", tr("install.extracted_to", &[&package_dir.display()]));

    // Step 1.5: 选择与包版本匹配的内置补丁集。上游内容随版本漂移（如
    // 0.7.0-exp.1 起 CodeAnalysis 下的 DLL/.meta 全部加了 `UnityPipeline.` 前
    // 缀），静态补丁无法跨版本通吃；规则表见 build.rs `PATCH_SET_RULES`。
    let package_version = read_package_version(&package_dir)?;
    let patch_set = select_patch_set(&package_version)?;
    println!(
        "{}",
        tr("install.version_patch_set", &[&package_version, &patch_set])
    );

    // Step 2: materialize the patchs/ tree (system mirror + custom dir), then
    // load every patch file in apply order: all of system/<补丁集>/, then custom/.
    let patchs_root = prepare_patchs_tree(&cwd)?;
    let patch_sources = collect_patch_sources(&patchs_root, patch_set)?;
    let apply_order = patch_sources
        .iter()
        .map(|(s, _)| s.as_str())
        .collect::<Vec<_>>()
        .join(" → ");
    println!("{}", tr("install.apply_order", &[&apply_order]));

    let mut file_patches = Vec::new();
    for (source, path) in &patch_sources {
        file_patches.extend(
            load_patch(source, path)
                .with_context(|| tr("install.load_patch_failed", &[&source]))?,
        );
    }

    println!("{}", t("install.dry_run_checking"));
    match dry_run_patches(&file_patches, &package_dir) {
        Ok(()) => println!("{}", t("install.dry_run_ok")),
        Err(err) => {
            eprintln!(
                "{}",
                tr("install.no_patch_set", &[&package_version, &patch_set])
            );
            eprintln!("{}", tr("install.dry_run_target", &[&package_dir.display()]));
            eprintln!("{}", tr("install.dry_run_detail", &[&format!("{err:#}")]));
            eprintln!("{}", t("install.custom_patch_hint"));
            return Err(anyhow!("{}", t("install.dry_run_failed")));
        }
    }

    // Apply the patch for real.
    println!("{}", t("install.applying_patches"));
    apply_patches(&file_patches, &package_dir).context(t("install.apply_patches_failed"))?;
    println!("{}", t("install.patches_applied"));

    // Step 3: copy the patched package into the target project's Packages/ dir.
    let dest_dir = target_project.join("Packages").join(PACKAGE_ID);
    if dest_dir.exists() {
        println!(
            "{}",
            tr("install.cleaning_existing", &[&dest_dir.display()])
        );
        fs::remove_dir_all(&dest_dir).with_context(|| {
            tr("install.clean_dest_dir_failed", &[&dest_dir.display()])
        })?;
    }
    fs::create_dir_all(&dest_dir).with_context(|| {
        tr("install.create_dest_dir_failed", &[&dest_dir.display()])
    })?;
    println!(
        "{}",
        tr(
            "install.copying",
            &[&package_dir.display(), &dest_dir.display()]
        )
    );
    copy_dir_recursive(&package_dir, &dest_dir)
        .with_context(|| tr("install.copy_failed", &[&dest_dir.display()]))?;

    // Step 4: final summary.
    println!();
    println!("{}", t("install.all_done"));
    println!("{}", tr("install.summary_package_version", &[&chosen]));
    println!("{}", tr("install.summary_project", &[&target_project.display()]));
    println!("{}", tr("install.summary_target", &[&dest_dir.display()]));
    println!("{}", t("install.switch_to_unity"));
    println!();
    println!("{}", t("install.mcp_config_example"));
    if let Err(err) = crate::configure::print_mcp_config(Some(target_project.as_path())) {
        eprintln!(
            "{}",
            tr("install.gen_mcp_config_failed", &[&format!("{err:#}")])
        );
    }
    Ok(())
}

/// Strip trailing `.tgz` / `.tar.gz` from a tarball filename so we can name
/// the extraction directory after the archive.
fn tarball_stem(file_name: &str) -> String {
    let lower = file_name.to_ascii_lowercase();
    if let Some(stripped) = lower.strip_suffix(".tar.gz") {
        return file_name[..stripped.len()].to_owned();
    }
    if let Some(stripped) = lower.strip_suffix(".tgz") {
        return file_name[..stripped.len()].to_owned();
    }
    file_name.to_owned()
}

/// Create the runtime `patchs/` tree: `system/` is wiped and rebuilt as a
/// mirror of the embedded patches so upgrades propagate; `custom/` is created
/// once and never touched; README.md is written only if missing.
fn prepare_patchs_tree(base_dir: &Path) -> Result<PathBuf> {
    let root = base_dir.join(PATCHS_DIR_NAME);
    let system_dir = root.join(SYSTEM_DIR_NAME);
    let custom_dir = root.join(CUSTOM_DIR_NAME);
    fs::create_dir_all(&custom_dir)
        .with_context(|| tr("install.create_dir_failed", &[&custom_dir.display()]))?;

    let readme = root.join("README.md");
    if !readme.exists() {
        fs::write(&readme, t("install.patchs_readme"))
            .with_context(|| tr("install.write_readme_failed", &[&readme.display()]))?;
    }

    if system_dir.exists() {
        fs::remove_dir_all(&system_dir).with_context(|| {
            tr("install.clean_system_dir_failed", &[&system_dir.display()])
        })?;
    }
    fs::create_dir_all(&system_dir).with_context(|| {
        tr("install.create_system_dir_failed", &[&system_dir.display()])
    })?;
    for (set, name, bytes) in EMBEDDED_PATCHES {
        let dir = system_dir.join(set);
        fs::create_dir_all(&dir).with_context(|| {
            tr("install.create_patch_set_dir_failed", &[&dir.display()])
        })?;
        fs::write(dir.join(name), bytes)
            .with_context(|| tr("install.write_embedded_patch_failed", &[&set, &name]))?;
    }
    Ok(root)
}

/// Enumerate patch files in apply order: all `system/<补丁集>/*.patch` (sorted
/// by file name), then `custom/modify_unity_local_<N>.patch` sorted by N (gaps
/// fine). Other `.patch` files in `custom/` are warned and skipped.
fn collect_patch_sources(root: &Path, patch_set: &str) -> Result<Vec<(String, PathBuf)>> {
    let mut out = Vec::new();

    let system_dir = root.join(SYSTEM_DIR_NAME).join(patch_set);
    let mut system: Vec<PathBuf> = fs::read_dir(&system_dir)
        .with_context(|| {
            tr(
                "install.read_system_dir_failed",
                &[&patch_set, &system_dir.display()],
            )
        })?
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.extension().map_or(false, |e| e == "patch"))
        .collect();
    system.sort();
    for p in system {
        let name = p.file_name().unwrap().to_string_lossy().into_owned();
        out.push((format!("{SYSTEM_DIR_NAME}/{patch_set}/{name}"), p));
    }

    let custom_dir = root.join(CUSTOM_DIR_NAME);
    let mut custom: Vec<(usize, String, PathBuf)> = Vec::new();
    for entry in fs::read_dir(&custom_dir)
        .with_context(|| tr("install.read_custom_dir_failed", &[&custom_dir.display()]))?
    {
        let path = entry?.path();
        if path.extension().map_or(true, |e| e != "patch") {
            continue;
        }
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        let num = name
            .strip_prefix(CUSTOM_PATCH_PREFIX)
            .and_then(|s| s.strip_suffix(".patch"))
            .and_then(|s| s.parse::<usize>().ok());
        match num {
            Some(n) => custom.push((n, name, path)),
            None => println!(
                "{}",
                tr("install.skip_custom_patch", &[&name, &CUSTOM_PATCH_PREFIX])
            ),
        }
    }
    custom.sort_by(|a, b| a.0.cmp(&b.0).then_with(|| a.1.cmp(&b.1)));
    for (_, name, path) in custom {
        out.push((format!("{CUSTOM_DIR_NAME}/{name}"), path));
    }
    Ok(out)
}

/// Read the exact package version from the extracted `package/package.json`.
/// Patch-set selection cannot guess, so any failure here aborts the install.
fn read_package_version(package_dir: &Path) -> Result<String> {
    let path = package_dir.join("package.json");
    let raw = fs::read_to_string(&path).with_context(|| {
        tr("install.read_package_json_failed", &[&path.display()])
    })?;
    let value: serde_json::Value = serde_json::from_str(&raw)
        .with_context(|| tr("install.parse_package_json_failed", &[&path.display()]))?;
    value
        .get("version")
        .and_then(|v| v.as_str())
        .map(|v| v.to_owned())
        .ok_or_else(|| {
            anyhow!(
                "{}",
                tr("install.missing_version_field", &[&path.display()])
            )
        })
}

/// Pick the embedded patch set for a package version: the rule with the
/// highest `from <= package_version` wins; with no match, fall back to
/// `DEFAULT_PATCH_SET`. Unparseable versions are a hard error — applying the
/// wrong set would only fail later with a much more confusing dry-run report.
fn select_patch_set(package_version: &str) -> Result<&'static str> {
    let pkg = semver::Version::parse(package_version)
        .with_context(|| tr("install.parse_package_version_failed", &[&package_version]))?;
    let mut best: Option<(semver::Version, &'static str)> = None;
    for (set, from) in PATCH_SET_RULES {
        let from = semver::Version::parse(from)
            .with_context(|| tr("install.invalid_patch_set_from", &[&set, &from]))?;
        if pkg >= from && best.as_ref().map_or(true, |(b, _)| from > *b) {
            best = Some((from, set));
        }
    }
    Ok(best.map(|(_, set)| set).unwrap_or(DEFAULT_PATCH_SET))
}

/// One text file-patch resolved to a repo-relative path plus its hunks.
struct FilePatch {
    /// Where this patch came from, e.g. `system/legacy/modify_unity2022_1.patch`.
    source: String,
    /// Path relative to the extracted `package/` root, using OS separators.
    rel_path: PathBuf,
    /// Original path string from the patch header, for error messages.
    header_path: String,
    hunks: Vec<Hunk>,
}

/// Parse one .patch file into per-file hunks. Skips binary segments and headers
/// with unusable paths; those cases surface as errors so nothing gets silently
/// dropped like `patcher` did.
fn load_patch(source: &str, patch_path: &Path) -> Result<Vec<FilePatch>> {
    let raw = fs::read(patch_path)
        .with_context(|| tr("install.read_patch_failed", &[&source, &patch_path.display()]))?;
    let lines = splitlines(&raw).map(|l| l.to_vec());
    let mut out = Vec::new();
    for (idx, item) in parse_patches(lines).enumerate() {
        let plain = item.map_err(|e| {
            anyhow!(
                "{}",
                tr(
                    "install.hunk_parse_failed",
                    &[&source, &(idx + 1), &format!("{e:?}")]
                )
            )
        })?;
        let unified = match plain {
            PlainOrBinaryPatch::Plain(u) => u,
            PlainOrBinaryPatch::Binary(b) => {
                return Err(anyhow!(
                    "{}",
                    tr(
                        "install.binary_segment",
                        &[&source, &String::from_utf8_lossy(&b.0)]
                    )
                ));
            }
        };
        let header_path = String::from_utf8(unified.mod_name.clone())
            .map_err(|_| {
                anyhow!(
                    "{}",
                    tr("install.hunk_target_not_utf8", &[&source, &(idx + 1)])
                )
            })?;
        let rel_str = strip_ab_prefix(&header_path);
        if rel_str.is_empty() {
            return Err(anyhow!(
                "{}",
                tr("install.hunk_missing_target", &[&source, &(idx + 1)])
            ));
        }
        let rel_path = PathBuf::from(rel_str.replace('/', std::path::MAIN_SEPARATOR_STR));
        out.push(FilePatch {
            source: source.to_owned(),
            rel_path,
            header_path,
            hunks: unified.hunks,
        });
    }
    if out.is_empty() {
        return Err(anyhow!("{}", tr("install.no_text_hunks", &[&source])));
    }
    Ok(out)
}

/// Strip a leading `a/` or `b/` segment the way `git apply -p1` would.
fn strip_ab_prefix(path: &str) -> String {
    if let Some(rest) = path.strip_prefix("a/").or_else(|| path.strip_prefix("b/")) {
        rest.to_owned()
    } else {
        path.to_owned()
    }
}

/// Verify every hunk applies cleanly against `target_dir`, without writing.
fn dry_run_patches(patches: &[FilePatch], target_dir: &Path) -> Result<()> {
    let opts = ApplyOptions::default();
    for fp in patches {
        let path = target_dir.join(&fp.rel_path);
        let base = fs::read(&path).with_context(|| {
            tr(
                "install.read_target_failed_with_patch_path",
                &[&fp.header_path, &path.display()],
            )
        })?;
        let result = dry_run(&base, &fp.hunks, &opts);
        // `dry_run` always leaves `patched = None`, so `is_success()` is
        // useless here — count rejected hunks instead.
        let rejected = result.rejected().count();
        if rejected > 0 {
            return Err(anyhow!(
                "{}",
                tr(
                    "install.hunks_rejected",
                    &[&fp.source, &fp.header_path, &rejected]
                )
            ));
        }
    }
    Ok(())
}

/// Apply every hunk and write the patched content back to disk. Assumes
/// `dry_run_patches` has already succeeded so failures here are unexpected.
fn apply_patches(patches: &[FilePatch], target_dir: &Path) -> Result<()> {
    let opts = ApplyOptions::default();
    for fp in patches {
        let path = target_dir.join(&fp.rel_path);
        let base = fs::read(&path).with_context(|| {
            tr("install.read_target_failed", &[&path.display()])
        })?;
        let result = apply_fuzzy(&base, &fp.hunks, &opts);
        let rejected_count = result.rejected().count();
        let patched = result.patched.ok_or_else(|| {
            anyhow!(
                "{}",
                tr(
                    "install.apply_hunks_failed",
                    &[&fp.source, &fp.header_path, &rejected_count]
                )
            )
        })?;
        fs::write(&path, patched).with_context(|| {
            tr("install.write_patched_file_failed", &[&path.display()])
        })?;
    }
    Ok(())
}

/// Show a numbered list of running Unity Editors and let the user pick one.
/// Returns `Ok(None)` when the user cancels (input `0` or empty when no default).
fn pick_target_project() -> Result<Option<PathBuf>> {
    println!("{}", t("install.finding_editors"));
    let instances = discover_editor_instances().context(t("install.scan_editors_failed"))?;
    if instances.is_empty() {
        println!("{}", t("install.no_editors_found"));
        return Ok(None);
    }

    println!(
        "{}",
        tr("install.pick_project_header", &[&instances.len()])
    );
    let width = instances.len().to_string().len();
    for (idx, inst) in instances.iter().enumerate() {
        println!(
            "  {:>width$}. {}  (PID {})",
            idx + 1,
            inst.project_name,
            inst.pid,
            width = width
        );
        println!("     {}", inst.project_path.display());
    }
    println!();
    print!("{}", tr("install.pick_project_prompt", &[&instances.len()]));
    std::io::stdout().flush().ok();

    let mut line = String::new();
    std::io::stdin()
        .lock()
        .read_line(&mut line)
        .context(t("install.read_input_failed"))?;
    let trimmed = line.trim();
    if trimmed.is_empty() {
        println!(
            "{}",
            tr("install.pick_project_default", &[&instances[0].project_name])
        );
        return Ok(Some(instances[0].project_path.clone()));
    }
    if trimmed == "0" {
        return Ok(None);
    }
    let n: usize = trimmed
        .parse()
        .map_err(|_| anyhow!("{}", tr("install.invalid_choice", &[&trimmed])))?;
    if n < 1 || n > instances.len() {
        return Err(anyhow!("{}", tr("install.choice_out_of_range", &[&n])));
    }
    Ok(Some(instances[n - 1].project_path.clone()))
}

/// Recursively copy a directory tree. 根部的 `Tests/` 与 `Tests.meta` 只是包的
/// 单元测试素材，装进项目后没有用处，复制时直接跳过。
fn copy_dir_recursive(src: &Path, dst: &Path) -> Result<()> {
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let file_type = entry.file_type()?;
        let src_path = entry.path();
        let name = entry.file_name();
        if name == "Tests" || name == "Tests.meta" {
            continue;
        }
        let dst_path = dst.join(&name);
        if file_type.is_dir() {
            fs::create_dir_all(&dst_path)?;
            copy_dir_recursive(&src_path, &dst_path)?;
        } else if file_type.is_file() {
            fs::copy(&src_path, &dst_path).with_context(|| {
                tr(
                    "install.copy_file_failed",
                    &[&src_path.display(), &dst_path.display()],
                )
            })?;
        }
    }
    Ok(())
}


fn pick_version(
    opts: &Options,
    versions: &[String],
    latest: Option<&str>,
    _packument: &Packument,
) -> Result<String> {
    if let Some(explicit) = opts.version.as_deref() {
        if versions.iter().any(|v| v == explicit) {
            return Ok(explicit.to_owned());
        }
        return Err(anyhow!(
            "{}",
            tr(
                "install.version_not_found_with_available",
                &[&explicit, &versions.join(", ")]
            )
        ));
    }
    if opts.latest {
        let pick = latest
            .map(|s| s.to_owned())
            .or_else(|| versions.first().cloned())
            .ok_or_else(|| anyhow!("{}", t("install.cannot_resolve_latest")))?;
        return Ok(pick);
    }

    // Interactive picker.
    println!(
        "{}",
        tr("install.pick_version_header", &[&versions.len()])
    );
    let width = versions.len().to_string().len();
    for (idx, v) in versions.iter().enumerate() {
        let marker = if Some(v.as_str()) == latest { "  ← latest" } else { "" };
        println!("  {:>width$}. {v}{marker}", idx + 1, width = width);
    }
    let default_pick = latest.and_then(|l| versions.iter().position(|v| v == l)).unwrap_or(0);
    let default_version = &versions[default_pick];
    println!();
    print!(
        "{}",
        tr(
            "install.pick_version_prompt",
            &[&versions.len(), &default_version]
        )
    );
    std::io::stdout().flush().ok();

    let stdin = std::io::stdin();
    let mut line = String::new();
    stdin
        .lock()
        .read_line(&mut line)
        .context(t("install.read_input_failed"))?;
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return Ok(default_version.clone());
    }
    if let Ok(n) = trimmed.parse::<usize>() {
        if n >= 1 && n <= versions.len() {
            return Ok(versions[n - 1].clone());
        }
    }
    // Accept a version string directly.
    if versions.iter().any(|v| v == trimmed) {
        return Ok(trimmed.to_owned());
    }
    Err(anyhow!("{}", tr("install.invalid_choice", &[&trimmed])))
}

fn tarball_file_name(url: &str, version: &str) -> String {
    url.rsplit('/')
        .next()
        .filter(|s| !s.is_empty())
        .map(|s| s.to_owned())
        .unwrap_or_else(|| format!("{PACKAGE_ID}-{version}.tgz"))
}

pub(crate) fn download(url: &str, dest: &Path) -> Result<()> {
    let dest_str = dest
        .to_str()
        .ok_or_else(|| {
            anyhow!(
                "{}",
                tr("install.dest_path_not_utf8", &[&dest.display()])
            )
        })?;
    let status = Command::new("curl")
        .args([
            "-fSL",
            "--progress-bar",
            "--retry",
            "3",
            "--retry-delay",
            "1",
            "-o",
            dest_str,
            url,
        ])
        .stdin(Stdio::null())
        .status()
        .context(t("install.start_curl_failed_hint"))?;
    if !status.success() {
        return Err(anyhow!(
            "{}",
            tr(
                "install.curl_download_failed",
                &[&format!("{:?}", status.code())]
            )
        ));
    }
    Ok(())
}

pub(crate) fn extract_tarball(tarball: &Path, dest: &Path) -> Result<()> {
    let tarball_str = tarball
        .to_str()
        .ok_or_else(|| {
            anyhow!(
                "{}",
                tr("install.tarball_path_not_utf8", &[&tarball.display()])
            )
        })?;
    let dest_str = dest
        .to_str()
        .ok_or_else(|| {
            anyhow!(
                "{}",
                tr("install.dest_dir_not_utf8", &[&dest.display()])
            )
        })?;
    let status = Command::new("tar")
        .args(["-xzf", tarball_str, "-C", dest_str])
        .stdin(Stdio::null())
        .status()
        .context(t("install.start_tar_failed_hint"))?;
    if !status.success() {
        return Err(anyhow!(
            "{}",
            tr(
                "install.tar_extract_failed",
                &[&format!("{:?}", status.code())]
            )
        ));
    }
    Ok(())
}

pub(crate) fn http_get_text(url: &str) -> Result<String> {
    let output = Command::new("curl")
        .args(["-fsSL", url])
        .stdin(Stdio::null())
        .stderr(Stdio::piped())
        .stdout(Stdio::piped())
        .output()
        .context(t("install.start_curl_failed"))?;
    if !output.status.success() {
        let err = String::from_utf8_lossy(&output.stderr);
        return Err(anyhow!(
            "{}",
            tr(
                "install.curl_request_failed",
                &[&url, &format!("{:?}", output.status.code()), &err.trim()]
            )
        ));
    }
    String::from_utf8(output.stdout).context(t("install.registry_not_utf8"))
}

/// Stream the file through the sha1 crate. Kept as a bounded-buffer read so we
/// don't slurp a multi-MB tarball into memory just to hash it.
fn sha1_hex(path: &Path) -> Result<String> {
    use sha1::{Digest, Sha1};
    use std::io::Read;

    let mut file = fs::File::open(path)
        .with_context(|| tr("install.open_sha1_file_failed", &[&path.display()]))?;
    let mut hasher = Sha1::new();
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = file
            .read(&mut buf)
            .with_context(|| tr("install.read_sha1_file_failed", &[&path.display()]))?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(40);
    for byte in digest {
        use std::fmt::Write;
        write!(&mut hex, "{byte:02x}").unwrap();
    }
    Ok(hex)
}

/// Sort semver-ish versions newest first: compare release tuples numerically,
/// then treat pre-release tags (`-exp.1`) as older than a bare release.
fn sort_versions(mut versions: Vec<String>) -> Vec<String> {
    versions.sort_by(|a, b| cmp_version(b, a));
    versions
}

fn cmp_version(a: &str, b: &str) -> std::cmp::Ordering {
    let (a_main, a_pre) = split_pre(a);
    let (b_main, b_pre) = split_pre(b);
    let a_parts = parse_num_parts(a_main);
    let b_parts = parse_num_parts(b_main);
    for i in 0..a_parts.len().max(b_parts.len()) {
        let av = a_parts.get(i).copied().unwrap_or(0);
        let bv = b_parts.get(i).copied().unwrap_or(0);
        match av.cmp(&bv) {
            std::cmp::Ordering::Equal => continue,
            other => return other,
        }
    }
    // A bare release is newer than any pre-release with equal main parts.
    match (a_pre, b_pre) {
        (None, None) => std::cmp::Ordering::Equal,
        (None, Some(_)) => std::cmp::Ordering::Greater,
        (Some(_), None) => std::cmp::Ordering::Less,
        (Some(x), Some(y)) => x.cmp(y),
    }
}

fn split_pre(v: &str) -> (&str, Option<&str>) {
    match v.split_once('-') {
        Some((main, pre)) => (main, Some(pre)),
        None => (v, None),
    }
}

fn parse_num_parts(s: &str) -> Vec<u64> {
    s.split('.')
        .map(|p| p.parse::<u64>().unwrap_or(0))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verify the pure-Rust sha1 matches a known digest so regressions in the
    /// streaming buffer show up here rather than via a mismatched registry SHA.
    #[test]
    fn sha1_hex_matches_known_digest() {
        let tmp = std::env::temp_dir().join(format!(
            "unity_pipeline_sha1_test_{}.bin",
            std::process::id()
        ));
        std::fs::write(&tmp, b"abc").unwrap();
        let got = sha1_hex(&tmp).unwrap();
        let _ = std::fs::remove_file(&tmp);
        // sha1("abc") — the RFC 3174 canonical test vector.
        assert_eq!(got, "a9993e364706816aba3e25717850c26c9cd0d89d");
    }

    /// Verify `collect_patch_sources` ordering: `system/<补丁集>/` sorted by
    /// name first, then custom by numeric N (so `_10` comes after `_2`), gaps
    /// allowed, non-conforming custom names skipped.
    #[test]
    fn collect_patch_sources_orders_system_then_custom() {
        let tmp = std::env::temp_dir().join(format!(
            "unity_pipeline_collect_test_{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&tmp);
        let system = tmp.join(SYSTEM_DIR_NAME).join("legacy");
        let custom = tmp.join(CUSTOM_DIR_NAME);
        std::fs::create_dir_all(&system).unwrap();
        std::fs::create_dir_all(&custom).unwrap();
        std::fs::write(system.join("b.patch"), "").unwrap();
        std::fs::write(system.join("a.patch"), "").unwrap();
        std::fs::write(custom.join("modify_unity_local_2.patch"), "").unwrap();
        std::fs::write(custom.join("modify_unity_local_10.patch"), "").unwrap();
        std::fs::write(custom.join("modify_unity_local_1.patch"), "").unwrap();
        std::fs::write(custom.join("ignored.patch"), "").unwrap();

        let sources = collect_patch_sources(&tmp, "legacy").unwrap();
        let names: Vec<&str> = sources.iter().map(|(s, _)| s.as_str()).collect();
        assert_eq!(
            names,
            vec![
                "system/legacy/a.patch",
                "system/legacy/b.patch",
                "custom/modify_unity_local_1.patch",
                "custom/modify_unity_local_2.patch",
                "custom/modify_unity_local_10.patch",
            ]
        );
        let _ = std::fs::remove_dir_all(&tmp);
    }

    /// Version → patch-set selection: cutoffs are prerelease-aware
    /// (`0.7.0-exp.1 < 0.7.0`), highest matching `from` wins, older versions
    /// fall back to the default set.
    #[test]
    fn select_patch_set_matches_version_cutoffs() {
        assert_eq!(select_patch_set("0.6.9").unwrap(), "legacy");
        assert_eq!(select_patch_set("0.6.10").unwrap(), "legacy");
        // prerelease of the cutoff itself sorts below `from`
        assert_eq!(select_patch_set("0.7.0-exp.0").unwrap(), "legacy");
        assert_eq!(select_patch_set("0.7.0-exp.1").unwrap(), "v0.7");
        assert_eq!(select_patch_set("0.7.0").unwrap(), "v0.7");
        assert_eq!(select_patch_set("0.8.0").unwrap(), "v0.7");
    }

    /// Unparseable package versions abort instead of guessing a patch set.
    #[test]
    fn select_patch_set_rejects_unparseable_versions() {
        assert!(select_patch_set("not-a-version").is_err());
        assert!(select_patch_set("").is_err());
    }

    #[test]
    fn read_package_version_reads_package_json() {
        let tmp = std::env::temp_dir().join(format!(
            "unity_pipeline_pkgver_test_{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();
        std::fs::write(
            tmp.join("package.json"),
            r#"{"name":"com.unity.pipeline","version":"0.7.0-exp.1"}"#,
        )
        .unwrap();
        assert_eq!(read_package_version(&tmp).unwrap(), "0.7.0-exp.1");
        let _ = std::fs::remove_dir_all(&tmp);
    }

    /// End-to-end sanity check: for every pristine package extraction cached
    /// under `releases/downloads/` (or the tarball in `UNITY_TARBALL`), select
    /// the patch set for its version, then parse + dry-run + apply those
    /// embedded patches in-memory. Extractions already patched by a previous
    /// install run are skipped (their old-state no longer matches any set);
    /// the copy-out keeps the cache untouched either way. Skips silently when
    /// no pristine package is available.
    #[test]
    fn embedded_patch_applies_to_cached_packages() {
        let tmp = std::env::temp_dir().join(format!(
            "unity_pipeline_patch_test_{}",
            std::process::id()
        ));
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        // Candidate package roots: tarball extraction first, then every
        // already-extracted version in the project-local download cache.
        let mut candidates: Vec<PathBuf> = Vec::new();
        if let Some(v) = std::env::var_os("UNITY_TARBALL") {
            let tarball = PathBuf::from(v);
            assert!(tarball.exists(), "tarball missing at {}", tarball.display());
            let status = Command::new("tar")
                .args(["-xzf", tarball.to_str().unwrap(), "-C", tmp.to_str().unwrap()])
                .status()
                .expect("tar 未启动");
            assert!(status.success(), "tar 解压失败");
            candidates.push(tmp.join("package"));
        } else {
            let downloads =
                PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("releases/downloads");
            if let Ok(entries) = std::fs::read_dir(&downloads) {
                candidates.extend(
                    entries
                        .filter_map(|e| e.ok().map(|e| e.path()))
                        .filter(|p| p.is_dir() && p.join("package").join("package.json").exists())
                        .map(|p| p.join("package")),
                );
            }
            candidates.sort();
        }
        if candidates.is_empty() {
            eprintln!("skip: no UNITY_TARBALL and no extracted package under releases/downloads");
            return;
        }

        for src in candidates {
            // A previous install run patches the extraction in place, so a
            // dirty cache no longer matches any patch set's old-state.
            let asset_cs = src.join("Editor/Commands/Assets/AssetCommands.cs");
            if std::fs::read_to_string(&asset_cs)
                .map(|s| s.contains("UNITY_2022_3"))
                .unwrap_or(false)
            {
                eprintln!("skip dirty cache: {}", src.display());
                continue;
            }

            let dest = tmp.join(format!("case-{}", src.parent().unwrap().file_name().unwrap().to_string_lossy()));
            std::fs::create_dir_all(&dest).unwrap();
            copy_dir_recursive(&src, &dest).expect("复制已解压包失败");

            let package_version = read_package_version(&dest).expect("读取包版本失败");
            let patch_set = select_patch_set(&package_version).expect("选择补丁集失败");
            eprintln!("end-to-end against {package_version} → patch set {patch_set}");

            let mut patches = Vec::new();
            for (set, name, bytes) in
                EMBEDDED_PATCHES.iter().filter(|(s, _, _)| *s == patch_set)
            {
                let patch_path = tmp.join(format!("{set}-{name}"));
                std::fs::write(&patch_path, bytes).unwrap();
                patches.extend(
                    load_patch(&format!("system/{set}/{name}"), &patch_path)
                        .expect("load_patch 应成功"),
                );
            }
            // 每个集合都是 modify_unity2022_1.patch 贡献 9 段 + patch 2 贡献 2 段
            // + patch 3 贡献 1 段。
            assert_eq!(patches.len(), 12, "预期 12 段 file-patch");

            dry_run_patches(&patches, &dest).expect("dry_run 应通过");
            apply_patches(&patches, &dest).expect("apply 应成功");

            // Sanity: the applied patch introduced a `UNITY_2022_3` guard.
            let cs =
                std::fs::read_to_string(dest.join("Editor/Commands/Assets/AssetCommands.cs"))
                    .unwrap();
            assert!(
                cs.contains("UNITY_2022_3"),
                "patch 后的文件应包含 UNITY_2022_3 宏"
            );
            // Sanity (v0.7 set): serializedVersion downgraded, and the
            // Unsafe .meta's platformData block must be byte-identical to
            // CSharp's (Editor-only). Guards against malformed block
            // reconstruction — a missing `settings:` line once made Unity
            // uncheck every platform for the Unsafe plugin.
            if patch_set == "v0.7" {
                let meta_dir = dest.join("Runtime/Plugins/CodeAnalysis");
                let platform_block = |name: &str| -> Vec<String> {
                    let text =
                        std::fs::read_to_string(meta_dir.join(name)).unwrap();
                    let mut out = Vec::new();
                    let mut in_block = false;
                    for line in text.lines() {
                        if line == "  platformData:" {
                            in_block = true;
                            continue;
                        }
                        if line.starts_with("  userData:") {
                            in_block = false;
                        }
                        if in_block {
                            out.push(line.to_owned());
                        }
                    }
                    out
                };
                let unsafe_meta = std::fs::read_to_string(
                    meta_dir.join(
                        "UnityPipeline.System.Runtime.CompilerServices.Unsafe.dll.meta",
                    ),
                )
                .unwrap();
                assert!(
                    unsafe_meta.contains("serializedVersion: 2"),
                    "patch 后的 .meta 应包含 serializedVersion: 2"
                );
                assert_eq!(
                    platform_block(
                        "UnityPipeline.System.Runtime.CompilerServices.Unsafe.dll.meta"
                    ),
                    platform_block(
                        "UnityPipeline.Microsoft.CodeAnalysis.CSharp.dll.meta"
                    ),
                    "Unsafe 的 platformData 块应与其余 Roslyn .meta 一致（Editor-only）"
                );
            }
        }
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
